version: "3.3"

services:
  
  vault-server:
    image: vault:latest
    restart: always
    container_name: vault-server
    ports:
      - "${VAULT_PORT}:8200"
    environment:
      VAULT_ADDR: "${VAULT_ADDR}"
      VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_DEV_ROOT_TOKEN_ID}"
    cap_add:
      - IPC_LOCK
    volumes:
    - ./config:/vault/config
    - ./data:/vault/data
    - ./logs:/vault/logs
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 5s
      timeout: 1s
      retries: 5
